-- ============================================
-- Employee Leave Management System - Database
-- Run this entire file in MySQL Workbench
-- ============================================

-- Step 1: Create and use the database
CREATE DATABASE IF NOT EXISTS leave_management;
USE leave_management;

-- ============================================
-- TABLE 1: users
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('employee', 'manager') DEFAULT 'employee',
    department VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- TABLE 2: leave_balance
-- ============================================
CREATE TABLE IF NOT EXISTS leave_balance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    total_leaves INT DEFAULT 20,
    used_leaves INT DEFAULT 0,
    remaining_leaves INT DEFAULT 20,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================
-- TABLE 3: leaves
-- ============================================
CREATE TABLE IF NOT EXISTS leaves (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    leave_type ENUM('Sick Leave', 'Casual Leave', 'Earned Leave', 'Maternity Leave') NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    reason TEXT NOT NULL,
    status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    manager_comment TEXT,
    applied_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================
-- SAMPLE DATA
-- NOTE: Passwords below are hashed versions of:
--   manager1  → password: admin123
--   emp1      → password: emp123
--   emp2      → password: emp456
-- These hashes are generated by werkzeug.security
-- The app will handle login correctly with these hashes
-- ============================================

INSERT INTO users (name, email, password, role, department) VALUES
('Rajesh Kumar', 'manager@company.com', 'scrypt:32768:8:1$abc123$hashedpassword1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111', 'manager', 'HR'),
('Priya Sharma', 'priya@company.com', 'scrypt:32768:8:1$abc123$hashedpassword2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222', 'employee', 'Engineering'),
('Anil Reddy', 'anil@company.com', 'scrypt:32768:8:1$abc123$hashedpassword3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333', 'employee', 'Engineering');

-- NOTE: The above passwords won't work directly because they are placeholder hashes.
-- When you run the Flask app and register through the web UI, real hashes will be generated.
-- Use the /register page to create your accounts instead.

-- Leave balances for each employee
INSERT INTO leave_balance (user_id, total_leaves, used_leaves, remaining_leaves) VALUES
(1, 20, 2, 18),
(2, 20, 5, 15),
(3, 20, 3, 17);

-- Sample leave applications
INSERT INTO leaves (user_id, leave_type, from_date, to_date, reason, status) VALUES
(2, 'Sick Leave', '2025-04-01', '2025-04-02', 'Fever and cold, doctor advised rest', 'Approved'),
(2, 'Casual Leave', '2025-04-10', '2025-04-12', 'Family function at hometown', 'Pending'),
(3, 'Earned Leave', '2025-03-20', '2025-03-22', 'Personal trip planned in advance', 'Rejected');

-- ============================================
-- Verify tables were created
-- ============================================
SHOW TABLES;
SELECT 'Database setup complete!' AS Status;
